---

- name: Ensure that other Docker installations are removed
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Ensure that GPG keys can be added
  apt:
    name:
      - gpg
      - gpg-agent
    state: present
    update_cache: yes
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker's repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
- name: Install Docker
  apt:
    allow_unauthenticated: yes
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
- name: Prevent docker-ce from being upgraded
  dpkg_selections:
    name: docker-ce
    selection: hold
- name: Prevent docker-ce-cli from being upgraded
  dpkg_selections:
    name: docker-ce-cli
    selection: hold
- name: Ensure that Docker is enabled and running
  service:
    name: docker
    enabled: yes
    state: started
- name: Install bash completion
  apt:
    name:
      - bash-completion
- name: Add Docker's bash completion
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker-completion.sh
    mode: '0644'
- name: Add admins to docker group
  user:
    groups: docker
    append: yes
    name: "{{ item }}"
  loop: "{{ admin_accounts }}"
# python-is-python3 is only available on Ubuntu 20.04 and newer (?)
- name: Install Python packages
  apt:
    name:
      - python-is-python3
      - python3
      - python3-pip
      - python3-setuptools
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version == '20')
- name: Install Python packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version == '18')
# this requires prior successful installation of Python
- name: Install Docker SDK python package
  pip:
    name: docker
  ignore_errors: true
