---

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker's repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
    update_cache: yes
- name: Install Docker
  apt:
    force: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: Ensure that Docker is enabled and running
  service:
    name: docker
    enabled: yes
    state: started
- name: Install bash completion
  apt:
    name:
      - bash-completion
- name: Add Docker's bash completion
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
    dest: /etc/bash_completion.d/docker-completion.sh
    mode: '0644'
- name: Add admins to docker group
  user:
    groups: docker
    append: yes
    name: "{{ item }}"
  loop: "{{ admin_accounts }}"
- name: Install Python packages
  apt:
    name:
      - python-is-python3
      - python3
      - python3-pip
      - python3-setuptools
# this requires prior successful installation of Python
- name: Install Docker SDK python package
  pip:
    name: docker
  ignore_errors: true
