---
# tasks file for cmdb-agent

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
